            - name: Logseq Publish
  # You may pin to the exact commit or the version.
  # uses: pengx17/logseq-publish@7007321a8cb210169bf869006f785524e6c02bd4
  uses: pengx17/logseq-publish@0.1.8
  with:
    # export source
    src: # default is 
    # export destination
    dest: # default is www
    # Logseq version to use. Note, not all version are supported. Use "latest" if you are not sure what to put here.

    version: # default is latest
    # Whether or not to generate trace file for debugging.  

    trace: # optional, default is true
    # selected theme
    theme: # default is light
          
